@backend_HostAddress = http://localhost:5192

### GET all blog posts
GET {{backend_HostAddress}}/blogpost/
Accept: application/json

###

### POST a new blog post
POST {{backend_HostAddress}}/blogpost/
Content-Type: application/json
Accept: application/json

{
  "authorId": 1,
  "Content": "This is my second blog post, I hope it goes well!"
}

# {
#   "Id": 1,
#   "Author": {"Id": 3, "Name": "Alice23"},
#   "Content": "Hello, this is my very first blog post23!"
# }
