@backend_HostAddress = http://localhost:5192

### GET all blog posts
GET {{backend_HostAddress}}/blogpost/
Accept: application/json

###

### GET a blog post

GET {{backend_HostAddress}}/blogpost/1
Accept: application/json

### POST a new blog post
POST {{backend_HostAddress}}/blogpost/
Content-Type: application/json
Accept: application/json

{
  "authorId": 1
}

# {
#   "Id": 1,
#   "Author": {"Id": 3, "Name": "Alice23"},
#   "Content": "Hello, this is my very first blog post23!"
# }

###

### UPDATE a blog post
PATCH {{backend_HostAddress}}/blogpost/11
Content-Type: application/json
Accept: application/json

{
  "Id": 12,
  "authorId": 2
}

### DELETE a blog post

DELETE {{backend_HostAddress}}/blogpost/1
Accept: application/json









### GET all authors


GET {{backend_HostAddress}}/author
Accept: application/json


### GET specific author

GET {{backend_HostAddress}}/author/1
Accept: application/json

### PATCH / UPDATE an author

PATCH {{backend_HostAddress}}/author/1
Content-Type: application/json
Accept: application/json

{
  "Name": "Alisson"
}


### DELETE an author

DELETE {{backend_HostAddress}}/author/1
Accept: application/json


###
